Issue 814 : Name the zip file after the folder name
bpatrik/pigallery2 pull request #816
Opened 2024-01-20 17:40 UTC by fred1701d

The name of the zip when downloading a folder should be named after the folder.
For root, default will be gallery.zip

2024-02-06 22:30 UTC, bpatrik requested changes

2024-02-06 22:30 UTC, bpatrik commented on src/backend/middlewares/GalleryMWs.ts
> +    var contentDisposition = require('content-disposition')
please fix the lint errors.

2024-02-06 22:30 UTC, bpatrik commented on src/backend/middlewares/GalleryMWs.ts
> +      var zipName = directoryName;
please fix the lint errors.

2024-02-06 22:30 UTC, bpatrik commented on src/backend/middlewares/GalleryMWs.ts
> +    var contentDisposition = require('content-disposition')
Is this a new dependency to the project? It is not listed in the package.json
Can you reason about why this is needed?

2024-02-11 16:05 UTC, fred1701d commented on src/backend/middlewares/GalleryMWs.ts
> +    var contentDisposition = require('content-disposition')
I don't know how to fix it. I can decline my PR
I'm not a Node JS developer. Java is much better :-)

2024-02-11 16:06 UTC, fred1701d commented on src/backend/middlewares/GalleryMWs.ts
> +    var contentDisposition = require('content-disposition')
I don't know, that's something I found online.
I think I'll just drop my PR

2024-02-11 16:07 UTC, closed without merging