Fix for issue #794 (bugfix)
bpatrik/pigallery2 pull request #826
Opened 2024-02-05 22:00 UTC by grasdk

* Switched from ExifReader to exifr and updated tests and test material to fix issue [#794](https://github.com/bpatrik/pigallery2/issues/794)
* Removed dependency to ExifReader
* Updated .gitignore
* Minor clarification added to CONTRIBUTING.md

2024-02-05 22:05 UTC, grasdk commented
While doing this, I discovered a bug with png files having the "createDate" set to the file-date, even if they have metadata embedded. Exifr can read this date metadata from png files, so there are options to further utilize exifr for fixing issues.

I will look into this, but wanted to separate it from the fix of the issue.

2024-02-06 22:37 UTC, bpatrik requested changes
Thank you! Nice contribution!


Can you please also remove any unused dependencies from the package.json (and also from the lock file)

2024-02-06 22:37 UTC, bpatrik commented on .gitignore
> +test/folder-reset.js
Can you just use wildcard instead, like: test/*.js etc?

2024-02-07 06:02 UTC, grasdk commented
> Thank you! Nice contribution!
> 
> Can you please also remove any unused dependencies from the package.json (and also from the lock file)

Sure. I will do this asap. Hopefully tonight (it's morning here, now). Also the .gitignore

2024-02-08 22:12 UTC, bpatrik commented
Thank you!

2024-02-08 22:12 UTC, merged