Unify backend logging and separate log levels for relevant error types
bpatrik/pigallery2 pull request #863
Opened 2024-03-29 07:07 UTC by sarayourfriend

Potentially fixes #514 (depending on interpretation of what would resolve that issue)

I wrote a [little in the issue of my exploration of this problem](https://github.com/bpatrik/pigallery2/issues/514#issuecomment-2026765422). Basically, I think the issue comes down to a matter of opinion about what should and shouldn't be logged at the "warning" level.

In my experience, authentication errors are not worth logging at all in production environments, precisely because they happen so frequently with credentials stuffing or bots crawling for exposed WordPress/Drupal/Django/whatever admin pages. It is trivial to detect these based on request logs and response status code volumes, and even from pigallery2's own access logs, if enabled (though, those are debug-level so are a different question).

I admit that is an opinion, but for well configured servers, these logs will either unnecessarily frighten people who don't have experience running application services in production environments or fill up your log files and potentially cost you additional money in your log querying/transport solution if you have one. I run applications at a warn level in production, and wouldn't expect that to include anything other than predicted-but-unusual/notable/potentially-bad cases (contrasted to errors which would be unhandled edge cases/bugs).

To reflect that, this PR does a few things:

1. It defines a log level for each `ErrorCodes` value, or at least defines specific ones for several error types and defaults to warn. This has an added benefit of actually increasing the log level for what may be true error-level stuff, though that's definitely something that needs input. I'm not familiar with all the features of pigallery2 as I only use the simplest ones myself, and haven't run into most of these edge cases to say whether they're definitely errors or warnings. This is easy to change though, just change which set of cases any particular error code is grouped into.
2. It combines logs that were for the same application event but spread across multiple log events, often, I think, because of a typing issue. It looks like `console.error` and `console.log` were used almost exclusively for passing error objects and relying on `console`'s serialization of objects. The Logger class's functions didn't allow for this due to far more restrictive types in the function signatures than the console functions take. By loosening the Logger class's functions to match the Console functions, that's no longer an issue. These events are easily unified into a single log event to match the single application event.
    - I didn't do this in _all_ cases, namely the extension errors, mostly because those seem to be developer logs, and aren't application events so much as configuration errors... meaning, I don't think it's likely they would be relevant in production unless something were obviously wrong, rather than if you were monitoring error-level logs as a metric in production.
3. It removes some calls to log that duplicated the rendering middleware's own logging of errors.

I also found some dead code in the rendering middleware's error logging routine and removed it. I'll add a comment explaining why it is dead code to clarify.

Also, I want to clarify again that this is just my interpretation of what the appropriate logging levels are for these kinds of authentication errors, based on my experience developing and running several different internet-facing applications in production. Happy to be wrong about this for pigallery2! Not all applications have the same logging needs.

I look forward to any comments on the PR :slightly_smiling_face: I really like pigallery2 and think it's a great application, and am excited to contribute any way I can.

2024-03-30 20:19 UTC, bpatrik requested changes

2024-03-30 20:19 UTC, bpatrik commented on src/backend/Logger.ts
> +export type LoggerArgs = Parameters<Console["log"]>[0]
This is not exactly true. There was a recent PR that made it possible to use string returning functions as parameter, so the args do not equal with console.log.

2024-03-30 20:19 UTC, bpatrik commented on src/backend/model/database/GalleryManager.ts
> +            .catch(Logger.error);
Are you certain this would work the same way?


To my memories, console.error properly prints the stacktrace of an error. It also prints errors to stderr, not to stdout.  not sure if the 2nd is an issue, but the stacktrace is needed.

Loggger uses console.log only.

2024-03-30 20:19 UTC, bpatrik commented on src/backend/model/extension/ExtensionConfigWrapper.ts
> +import {Logger} from '../../Logger';
This is very tricky here.  This class loads the config. Logger depends on config. Using logger in this class would end in circular dependency,  so it could not be used here.

2024-03-30 20:19 UTC, bpatrik commented on src/backend/model/messenger/StdoutMessenger.ts
> -    console.log(media.map(m => m.thumbnailPath));
This class is kind dummy/sample class. Its purpose is to print some data to the sdtout without any other text, so its not really logging here.

2024-03-30 20:50 UTC, bpatrik commented
Thank you very much for your contribution. 

I don't mind if login or other scraper errors are supressed . Moving /api /pgapi and updating nginx path helped a lot to reduce these attempts.

2024-03-30 22:19 UTC, sarayourfriend commented on src/backend/Logger.ts
> +export type LoggerArgs = Parameters<Console["log"]>[0]
True, `console.log`'s args are all `any`, so it happens to work. I could change this either to explicitly `any`, or try to expand the types of the original `LoggerArgs` to accept things like the `ErrorDTO`. Adding `| any` to the existing type reduces it to just `any` in the end anyway.

The underlying implementation of the `Logger` functions remains the same, so passing a string-returning function will continue to work exactly as before... there's just no indication in the types that that's an _expected_ input :thinking: 

A type something like `string | number | (() => string) | object` might capture everything correctly and still indicate in the type that a string-returning function is expected. What do you think?

2024-03-30 22:23 UTC, sarayourfriend commented on src/backend/model/database/GalleryManager.ts
> +            .catch(Logger.error);
You're right, there is a difference. I considered changing the `Logger.error` implementation to use stderr to match `console.error`'s behaviour, and make things more consistent with typical expectations for node console. In reading some of the related issues, however, I read [this comment of yours](https://github.com/bpatrik/pigallery2/issues/519#issuecomment-1344832911) where you said the app "only prints logs to stdout". I assumed this was the intention, but I should have clarified that in the PR description! I did not consider the difference in the stack trace printing, total oversight, thank you for catching it.

If it's not necessarily a strict intention to send everything to stdout, then changing the implementation of `Logger.error` to use `console.error` would keep the behaviour of places like this equivalent (other than adding the `Logger.error` prefix, but would introduce changes in the behaviour for existing cases of `Logger.error`.

What's your preference here? I can also remove this clean up from the PR, it's a bit outside the specific scope of changing the log-level of the relevant error types :thinking:

2024-03-30 22:24 UTC, sarayourfriend commented on src/backend/model/messenger/StdoutMessenger.ts
> -    console.log(media.map(m => m.thumbnailPath));
I'll revert this change.

2024-03-30 22:25 UTC, sarayourfriend commented on src/backend/model/extension/ExtensionConfigWrapper.ts
> +import {Logger} from '../../Logger';
Oh, I didn't catch that, I guess I didn't test with an extension locally. I'll just revert this along with the other logging "clean ups" as outside the scope of the log-level changes.

2024-03-30 22:26 UTC, sarayourfriend commented
Thanks for the revievw @bpatrik. I mentioned in a couple of the review comments, but to clarify, I'll go ahead and make the following changes:

1. I'll set back `LoggerArgs` to the original type with `| object` added, to allow passing error objects for to leveral console.log's printing.
2. I'll undo the broader logging "clean up" and stick to just the log-level changes. That'll cut the scope and make this easier to review. Sorry for the noise there!

2024-03-30 22:39 UTC, sarayourfriend commented on src/backend/Logger.ts
> +export type LoggerArgs = Parameters<Console["log"]>[0]
Ah, trying this locally, `| object` widens the type to essentially `any`. `() => 123` is accepted now, when previously it wouldn't have been. Incidentally, it does work, because there's nothing in the `Logger.log` function that expects the return type of the functions to be a string specifically, it just needs to be something `console.log` will accept as an argument (which is `any`).

A narrower type like `Record<any, unknown>` doesn't allow for the Error objects, but adding a further `| Error` keeps the stronger argument type than `any` while still opening up passing the error objects in `RenderingMWs`.

```ts
export type LoggerArgs = (string | number | (() => string) | Record<any, unknown> | Error);
const t: LoggerArgs = () => 123  // => not assignable
```

```ts
export type LoggerArgs = (string | number | (() => string) | object);
const t: LoggerArgs = () => 123 // => allowed, `LoggerArgs` is basically `any`
```

It feels a little fiddly to do it this way, considering `console.log` takes `any` anyway, but it's nice to have the types stay the same and reduce the potential scope of changes.

2024-03-30 22:50 UTC, sarayourfriend commented on src/backend/model/database/GalleryManager.ts
> +            .catch(Logger.error);
Resolving the comment as I've reverted these changes in the PR.

2024-03-30 22:51 UTC, sarayourfriend commented on src/backend/model/messenger/StdoutMessenger.ts
> -    console.log(media.map(m => m.thumbnailPath));
Reverted the change.

2024-03-30 22:53 UTC, sarayourfriend commented on src/backend/Logger.ts
> -export type logFN = (...args: (string | number | (() => string))[]) => void;
This type duplicated the `LoggerFunction` type below, and was only used in one place, so I consolidated them.

2024-03-30 22:55 UTC, sarayourfriend commented on src/backend/middlewares/RenderingMWs.ts
> -        }
This code is dead. `err.detailsStr` is deleted on 139, so the conditionl will always evaulate to false and the block won't run.

I'm not familiar with this code to interpret what the _intention_ was. If you know what it's meant to do @bpatrik I can update it to do that instead of removing the code.

2024-04-01 11:09 UTC, bpatrik commented on src/backend/middlewares/RenderingMWs.ts
> -        }
To be honest I can't remember either. 

Removing it sounds good to me.

2024-04-01 11:10 UTC, bpatrik approved these changes

2024-04-01 11:10 UTC, bpatrik commented
Thank you! 

This change looks good to me.

2024-04-01 11:10 UTC, merged