updated image-size dependency to read dimensions from heic file
bpatrik/pigallery2 pull request #879
Opened 2024-04-05 22:33 UTC by grasdk

Added extra not-null assurance for image width and height

updated image-size library (still has some bugs, though).

2024-04-05 22:54 UTC, grasdk commented
Fix for https://github.com/bpatrik/pigallery2/issues/877

It's not a complete fix though, but it should stop the SQL error.

However, the latest version of the image-size module does not correctly report the size of the test heic-image that was added. I adapted the test to work with what image-size returned.

2024-04-08 16:14 UTC, bpatrik requested changes
Some not important feedback. Feel free to discard

2024-04-08 16:14 UTC, bpatrik commented on src/backend/model/fileaccess/MetadataLoader.ts
> +        if (metadata.size.width == undefined || metadata.size.width == null) {
Maybe isNaN?

2024-04-08 16:56 UTC, grasdk commented on src/backend/model/fileaccess/MetadataLoader.ts
> +        if (metadata.size.width == undefined || metadata.size.width == null) {
isNaN(null) is actually false, but replacing the == undefined with isNaN is a good idea, if the value should somehow ever be contaminated with values that are not numbers. :)

I will change this, but since I expect a bit of conflict with my other PR, I might as well fix these conflicts and this comment in one go :)

2024-04-11 21:07 UTC, merged