Sharing key increase complexity
bpatrik/pigallery2 pull request #901
Opened 2024-05-11 12:03 UTC by VirtualGit

Add a sharing key complexity setting to generate more complex keys.
Keys too long will be displayed with an ellipsis.
(refs #883)
That's my first github PR. I updated my branch twice so there are merge commits. Tell me if this is ok or if you want I make a new more clean branch.
Thanks

2024-05-12 21:01 UTC, bpatrik requested changes

2024-05-12 21:01 UTC, bpatrik commented on src/common/config/public/ClientConfig.ts
> +    description: $localize`The longer the keys are, the more secure the share links will be.`,
I would rather say something like: that longer the key, harder is it to guess it. The current phrasing implies better underlying security with longer keys.

I would also add that using lenght of 8 takes 70000 years to try all permutation (assuming the server can serve a request in 10s), which should be complex enough.

Also i would add a note that changing this number won't invalidate existing sharing

2024-05-12 21:02 UTC, bpatrik commented
Nice! Thank you! I made a comment on the config description. Otherwise it looks good to me.

2024-05-18 20:19 UTC, VirtualGit commented on src/common/config/public/ClientConfig.ts
> +    description: $localize`The longer the keys are, the more secure the share links will be.`,
Ok, I changed to "The longer the keys are, the harder they are to guess.".
Do you want I add "Changing this number won't invalidate existing sharing" in the setting description ?

2024-05-18 20:22 UTC, VirtualGit commented on src/common/config/public/ClientConfig.ts
> +    description: $localize`The longer the keys are, the more secure the share links will be.`,
Also, should I do a new PR with these changes, or can I update this one ?

2024-05-21 20:31 UTC, bpatrik commented on src/common/config/public/ClientConfig.ts
> +    description: $localize`The longer the keys are, the more secure the share links will be.`,
Yes please add that text too. 
Yes you should be able merge the changes here too.

2024-06-09 10:35 UTC, closed without merging

2024-06-09 10:42 UTC, VirtualGit commented
Sorry for the close, I had some troubles with PR. I'm just submitting a new one.